apiVersion: apps/v1
kind: Deployment
metadata:
  name: newempapi
  namespace: default
  labels:
    'backstage.io/kubernetes-id': 'newempapi'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newempapi
  template:
    metadata:
      labels:
        app: newempapi
        'backstage.io/kubernetes-id': 'newempapi'
    spec:
      imagePullSecrets:
      - name: registry-auth
      containers:
        - name: newempapi
          image: idpdeveacr.azurecr.io/newempapi:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: newempapi
  namespace: default
  labels:
    #tekton.dev/pipelines: default/springboot-pipeline
    'backstage.io/kubernetes-id': 'newempapi'
spec:
  type: LoadBalancer
  selector:
    app: newempapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
